import React, { useState, useEffect } from 'react';
import Navbar from './components/Navbar';
import Home from './pages/Home';
import Analyze from './pages/Analyze';
import Report from './pages/Report';
import HowItWorks from './pages/HowItWorks';
import Privacy from './pages/Privacy';
import Compare from './pages/Compare';
import { MOCK_CLAIM_DATA } from './data/mockClaimData';
import { ShieldCheck } from 'lucide-react';

export default function App() {
  const [currentPath, setCurrentPath] = useState('/');
  const [theme, setTheme] = useState(() => {
    return localStorage.getItem('claimshield_theme') || 'dark';
  });
  const [claimContext, setClaimContext] = useState(null);
  const [reportData, setReportData] = useState(MOCK_CLAIM_DATA);

  // Synchronize theme attribute on root element & localStorage
  useEffect(() => {
    document.documentElement.setAttribute('data-theme', theme);
    localStorage.setItem('claimshield_theme', theme);
  }, [theme]);

  const toggleTheme = () => {
    setTheme(prev => (prev === 'light' ? 'dark' : 'light'));
  };

  const navigate = (path) => {
    setCurrentPath(path);
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  const handleStartAnalysis = async (userInput) => {
    setClaimContext(userInput);
    navigate('/analyze');
    
    try {
      // Prepare form data for the FastAPI backend
      const formData = new FormData();
      formData.append('incident', userInput.incidentText || 'Unknown incident');
      
      // If a real file was uploaded, attach it. Otherwise attach a dummy blob to satisfy FastAPI file requirements.
      if (userInput.uploadedFile) {
        formData.append('policy', userInput.uploadedFile);
      } else {
        const dummyPdf = new Blob(['dummy pdf content'], { type: 'application/pdf' });
        formData.append('policy', dummyPdf, 'policy.pdf');
      }

      // Fetch from your live Python backend
      const response = await fetch('http://127.0.0.1:8001/api/v1/analyze', {
        method: 'POST',
        body: formData,
      });

      if (response.ok) {
        const data = await response.json();
        
        // Map the FastAPI response format to the React UI format
        const formattedData = {
          auditId: data.analysis_id || "AUDIT-2026-LIVE",
          timestamp: new Date().toISOString(),
          riskLevel: data.risk_level || "MEDIUM",
          statusLabel: "ATTENTION REQUIRED",
          issueCount: (data.risks || []).length,
          summary: "Live audit results generated by Gemma4 and Local Rules Engine.",
          
          findings: (data.risks || []).map((r, i) => ({
            id: `F00${i+1}`,
            severity: r.severity,
            category: r.category,
            title: r.title,
            description: r.interpretation,
            interpretation: r.interpretation,
            recommendedAction: r.recommended_action,
            action: r.recommended_action,
            policyEvidence: r.policy_evidence,
            clauseRef: r.policy_reference,
            userContext: r.user_evidence
          })),
          
          deadline: {
            title: "Notification Check",
            clauseRef: "General Terms",
            initialSeconds: 67335,
            description: "Time remaining based on incident"
          },
          
          actionChecklist: (data.actions || []).map((a, i) => ({
            id: `c${i+1}`,
            task: a.task,
            priority: a.priority,
            completed: false
          })),
          
          emailDraft: {
            subject: "Urgent Notification",
            body: data.email_draft || "Dear TPA, please see attached claim.",
            disclaimer: "AI-generated draft."
          }
        };

        setReportData(formattedData);
      } else {
        console.error("Backend returned an error");
        setReportData({
          auditId: "ERROR",
          timestamp: new Date().toISOString(),
          riskLevel: "CRITICAL",
          statusLabel: "CONNECTION ERROR",
          issueCount: 0,
          summary: "The backend server returned an error.",
          findings: [],
          actionChecklist: [],
          emailDraft: { subject: "Error", body: "Error", disclaimer: "" }
        });
      }
    } catch (error) {
      console.error("Failed to connect to backend", error);
      setReportData({
          auditId: "ERROR",
          timestamp: new Date().toISOString(),
          riskLevel: "CRITICAL",
          statusLabel: "CONNECTION ERROR",
          issueCount: 0,
          summary: "Failed to connect to the FastAPI backend. Is it running on port 8000?",
          findings: [],
          actionChecklist: [],
          emailDraft: { subject: "Error", body: "Error", disclaimer: "" }
      });
    } finally {
      // Wait for at least 3 seconds so the user sees the progress animation
      // or navigate immediately if it took longer
      navigate('/report');
    }
  };

  const handleStartOver = () => {
    setClaimContext(null);
    setReportData(MOCK_CLAIM_DATA);
    navigate('/');
  };

  const renderCurrentView = () => {
    switch (currentPath) {
      case '/compare':
        return <Compare onGoHome={() => navigate('/')} />;
      case '/analyze':
        return <Analyze />;
      case '/report':
        return <Report reportData={reportData} onStartOver={handleStartOver} />;
      case '/how-it-works':
        return <HowItWorks onGoHome={() => navigate('/')} />;
      case '/privacy':
        return <Privacy />;
      case '/':
      default:
        return <Home onStartAnalysis={handleStartAnalysis} onNavigate={navigate} />;
    }
  };

  return (
    <div className="app-container">
      <Navbar 
        currentPath={currentPath} 
        onNavigate={navigate}
        theme={theme}
        onToggleTheme={toggleTheme}
      />

      {renderCurrentView()}

      <footer className="footer">
        <div style={{ 
          maxWidth: 'var(--max-width-wide)', 
          margin: '0 auto',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          flexWrap: 'wrap',
          gap: '1rem'
        }}>
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.4rem', fontWeight: 700, color: 'var(--text-primary)', marginBottom: '0.2rem' }}>
              <ShieldCheck size={16} style={{ color: 'var(--color-accent)' }} />
              <span>CLAIMSHIELD</span>
            </div>
            <div style={{ fontSize: '0.8125rem', color: 'var(--text-muted)' }}>
              Understand your policy. Protect your claim.
            </div>
          </div>

          <div style={{ display: 'flex', gap: '1.25rem', fontSize: '0.8125rem' }}>
            <button onClick={() => navigate('/how-it-works')} style={{ background: 'none', border: 'none', color: 'var(--text-secondary)', cursor: 'pointer' }}>
              How it works
            </button>
            <button onClick={() => navigate('/privacy')} style={{ background: 'none', border: 'none', color: 'var(--text-secondary)', cursor: 'pointer' }}>
              Privacy
            </button>
            <a href="https://github.com" target="_blank" rel="noreferrer" style={{ color: 'var(--text-secondary)' }}>
              GitHub
            </a>
          </div>
        </div>

        <div style={{ 
          maxWidth: 'var(--max-width-wide)', 
          margin: '0.85rem auto 0', 
          paddingTop: '0.85rem', 
          borderTop: '1px solid var(--border-color)',
          fontSize: '0.75rem',
          color: 'var(--text-muted)',
          textAlign: 'center'
        }}>
          AI-assisted analysis · Not legal advice
        </div>
      </footer>
    </div>
  );
}
